FROM node:lts
ENV NODE_ENV production
## Environment ##
ENV REPO_URL https://github.com/boardsource/docs.git
ENV REPO_FOLDER docs
## Server ##
ENV PORT 8081
ENV HOST localhost
## Setup jet-logger ##
ENV JET_LOGGER_MODE FILE
ENV JET_LOGGER_FILEPATH jet-logger.log
ENV JET_LOGGER_TIMESTAMP TRUE
ENV JET_LOGGER_FORMAT LINE
## Authentication ##
# SECURE_COOKIE 'false' here for demo-ing. But ideally should be true.
ENV COOKIE_DOMAIN localhost
ENV COOKIE_PATH /
ENV SECURE_COOKIE false
ENV JWT_SECRET BOARDSOURCEPRIVATE
ENV COOKIE_SECRET BOARDSOURCEPRIVATE
# expires in 3 days
ENV COOKIE_EXP 259200000

WORKDIR /app
EXPOSE 8081

COPY . .
RUN npm install --include=dev
RUN npm run build 


CMD ["npm","run","start"]